version: '3'

services:
  app-backend:
    image: node:15
    container_name: app-backend
    command: bash -c "npm install && npm run migrations && npm start"
    working_dir: /app
    volumes:
      - .:/app
    ports: 
      - 3000:3000
    links: 
      - app-database
    depends_on: 
      - app-database
      
  app-database:
    image: postgres
    container_name: app-database
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

